from aenum import Enum


class Queries(Enum):
    _init_ = 'value string'

    JAVACC = 1, 'Generated By:JavaCC: Do not edit this line.'
    XTEXT = 2, 'generated by xtext'
    EVO_SUITE = 3, 'tests automatically generated by EvoSuite'

    def __str__(self):
        return self.string


class CrawlerConfig:
    def __init__(self):
        self.QUERY = Queries.JAVACC
        self.DATASET_FOLDER = 'JavaCC'
        self.API_TOKEN = '<hidden>'
        self.PAGE_SIZE = 100
        self.N_PAGES = 10
        self.MIN_FILE_SIZE = 2000
        self.STEP_SIZE = 5000
        self.N_STEPS = 10
        self.MAX_FILE_COUNT = 10000
